services:
  node:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./nestjs-api:/app
    ports:
      - "3000:3000"
    networks:
      - app-network
    command: ["npm", "run", "start:dev"]
    environment:
      NODE_ENV: development

networks:
  app-network:
    driver: bridge
