services:
  node:
    container_name: node
    build: ./nestjs-api
    working_dir: /app
    volumes:
      - ./nestjs-api:/app
    ports:
      - "3000:3000"
    networks:
      - app-network

  db:
    container_name: db
    build: ./.docker/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
